---
- name: generic
  vars:
     port_contents: "{{ lookup('file', 'port') }}"
     NAME_contents: "{{ lookup('file', 'NAME') }}"
     cstate: "{{ cstate | default(started) }}"
  hosts: "{{ NAME_contents }}"
  sudo: True
  tasks:
  - name: MovieMasher Angular interface
    docker:
      name: "{{ NAME_contents }}"
      image: busybox
      state: "{{ cstate }}"
      restart_policy: always
      ports:
      - "{{ port_contents }}"
      volumes:
      - '/tmp:/tmp'
